package com.docklee.annotation.security;

import static java.lang.annotation.ElementType.ANNOTATION_TYPE;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Inherited;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import com.docklee.annotation.enums.SecuritySchemeIn;
import com.docklee.annotation.enums.SecuritySchemeType;
import com.docklee.annotation.extensions.Extensions;

/**
 * <p><b>Docklee</b> - Api Documentation</p>
 * <p>
 * The annotation <code>SecurityScheme</code> may be used at class level (also on multiple classes) to add securitySchemes to spec components section.
 * </p>
 * 
 * @author Antonio Neto [<()>] - Initial implementation.
 * @version 1.0.0
 * @since 03-11-2020 
 * @see <a href="https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#securitySchemeObject">Security Scheme (OpenAPI specification)</a>
 */
@Target(value={TYPE,ANNOTATION_TYPE})
@Retention(value=RUNTIME)
@Repeatable(value=SecuritySchemes.class)
@Inherited
public @interface SecurityScheme {

	/**
	 * The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
	 * @return String type.
	 * */
	SecuritySchemeType type();
	/**
	 * A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes. Applies to http ("bearer") type.
	 * @return String bearerFormat. 
	 * */
	String bearerFormat() default "";
	/**
	 * A short description for security scheme. CommonMark syntax can be used for rich text representation.
	 * @return String description.
	 * */
	String description() default "";
	/**
	 * The list of optional extensions.
	 * @return An optional array of extensions.
	 * */
	Extensions[] extensions() default {};
	/**
	 * Required. An object containing configuration information for the flow types supported. Applies to oauth2 type.
	 * @return OAuthFlows flows.
	 * */
	OAuthFlows flows() default @OAuthFlows;
	/**
	 * The location of the API key. Valid values are "query" or "header". Applies to apiKey type.
	 * @return String in.
	 * */
	SecuritySchemeIn in() default SecuritySchemeIn.DEFAULT;
	/**
	 * The name identifying this security scheme.
	 * @return String name.
	 * */
	String name() default "";
	/**
	 * Required. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL. Applies to openIdConnect.
	 * @return String openIdConnectUrl.
	 * */
	String openIdConnectUrl() default "";
	/**
	 * The name of the header or query parameter to be used. Applies to apiKey type. Maps to "name" property of Security Scheme (OpenAPI specification).
	 * @return String paramName.
	 * */
	String paramName() default "";
	/**
	 * A reference to a SecurityScheme defined in components securitySchemes.
	 * @return The reference.
	 * */
	String ref() default "";
	/**
	 * The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC 7235. Applies to http type.
	 * @return String scheme.
	 * */
	String scheme() default "";
	
}
